### ISSUE TITLE
[Enhancement] Camera Position Offset

### ISSUE THREAD

**Issue by Soufre** [moehreag/realistic-rowing#1] opened 2023-12-14 03:18 UTC
I love this mod, it makes boat transportation a lot more interesting but one peeve I have with it is that the camera position remains the same, which visually looks kind of distracting and a little silly when paired with mods like _First-person Model_.

I hope you could look into this if there's anything that can be done, if not then no biggie.
![image](https://github.com/moehreag/realistic-rowing/assets/96512010/9bf989b2-9dc3-4a8d-be15-35d7449878a9)

**Comment by moehreag** [comment] 2023-12-14 11:51
This is caused by *First-Person Model* moving the camera further in front of the actual body. Though I am not able to reproduce it to the extend your image shows:
![image](https://github.com/moehreag/realistic-rowing/assets/85403855/9e2c35d6-cd67-4401-aa32-fe376f90035e)

**Comment by Soufre** [comment] 2023-12-14 18:24
My FOV being at 90 was causing the First-person Model issue but it still looks a tad distracting even when playing with the mod alone.

![2023-12-14_10 20 04](https://github.com/moehreag/realistic-rowing/assets/96512010/09ef0ca5-5e6e-4799-986d-62e812ee6f53)
![2023-12-14_10 17 01](https://github.com/moehreag/realistic-rowing/assets/96512010/4ad7aec7-3610-4337-ba7e-69edcaf32bf7)

Top is vanilla, bottom is with the mod installed (though, I had to manually turn the boat around because of how the mod works).
Camera position remains as if the player model was still in the middle of the boat.

**Comment by moehreag** [comment] 2023-12-14 19:28
It's possible to move the passenger in the boat though this may not resolve the issue that the top of the torso is visible when turning around with Firstperson Model installed (although this is not an issue with this mod - it's also possible to see this when turning around outside of a boat). This mod does not change anything about the possible viewing radius when turning around in boats, it just mirrors the values (to match the player being turned around)

**Comment by Soufre** [comment] 2023-12-15 00:11
Another example posted below.

![2023-12-14_15 54 17](https://github.com/moehreag/realistic-rowing/assets/96512010/d97cc1f4-fdf0-4d35-8942-7557070b8323)
![2023-12-14_15 57 08](https://github.com/moehreag/realistic-rowing/assets/96512010/e73a9fab-05d9-4e6b-a7c2-ea6780d35882)
While the model of the player changed to fit the mod, the camera remains the same.
_(Not counting First-person Model as it doesn't change the model.)_

![2023-12-14_15 57 08](https://github.com/moehreag/realistic-rowing/assets/96512010/55e3bd86-5272-4721-ad52-afef87ede184)
**The red highlight is the camera perspective**, like you'd see in the base game.
Again, not sure if there's anything that can be done to solve this peeve, just thought it would be nice to point it out for any future tweaking.

You can close this issue if there's nothing that can be done.

**Comment by moehreag** [comment] 2023-12-15 00:22
As I said yes, it is possible to move the passenger attachments in the boat which would then move the camera as well but that won't fix the issue of the top of the torso of the player being visible

**Closed as completed** 2023-12-23 22:51 UTC
